"use client";
import type { Metadata } from "next";
import { Orbit } from "next/font/google";
import Link from "next/link";
import { NextUIProvider } from "@nextui-org/react";
import { Provider } from "react-redux";
import { store } from "./redux/store";
import "./globals.css";

const orbit = Orbit({
    subsets: ["latin"],
    weight: ["400"],
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ko">
            <head>
                <title>Theo Playground</title>
            </head>
            <body className={orbit.className}>
                <NextUIProvider>
                    <Provider store={store}>
                        <div className="flex flex-col w-screen h-screen p-10 bg-[url('/background.webp')] bg-cover bg-center">
                            <header>
                                <nav>
                                    <ul className="flex">
                                        <li className="text-2xl font-bold hover:underline">
                                            <Link href="/">HOME</Link>
                                        </li>
                                    </ul>
                                </nav>
                            </header>
                            <div className="flex grow">{children}</div>
                        </div>
                    </Provider>
                </NextUIProvider>
            </body>
        </html>
    );
}
