"use client";
// import type { Metadata } from "next";
import { Orbit } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import { Provider } from "react-redux";
import { store } from "./redux/store";
import { useEffect } from "react";
import { io } from "socket.io-client";
import { useAppDispatch, useAppSelector } from "./redux/hook";
import { setPlayer } from "./redux/playerSlice";
import { setSocket } from "./redux/socketSlice";
import { setPlayers } from "./redux/playersSlice";
import { setRooms } from "./redux/roomsSlice";
import { setRoom } from "./redux/roomSlice";
import { Header } from "@/components/layout/header";
import "./globals.css";
import { selectJoinModal } from "./redux/joinModalSlice";

const orbit = Orbit({
    subsets: ["latin"],
    weight: ["400"],
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

const App = ({ children }: { children: React.ReactNode }) => {
    const dispatch = useAppDispatch();
    const joinModal = useAppSelector(selectJoinModal);

    useEffect(() => {
        const socket = io("http://localhost:3001");
        socket.on("joinPlayground", (player) => {
            if (player) {
                dispatch(setPlayer(player));
                joinModal.onClose();
                console.log(joinModal.onClose);
            } else {
                alert("이미 존재하는 이름입니다.");
            }
        });
        socket.on("sendPlayers", (players) => {
            dispatch(setPlayers({ players: players }));
        });
        socket.on("sendRoom", (room) => {
            dispatch(setRoom(room));
        });
        socket.on("sendRooms", (rooms) => {
            dispatch(setRooms({ rooms: rooms }));
        });
        dispatch(
            setSocket({
                socket: socket,
            })
        );
    }, [joinModal]);
    return <div className="flex grow">{children}</div>;
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ko">
            <head>
                <title>Theo Playground</title>
            </head>
            <body className={orbit.className}>
                <NextUIProvider>
                    <Provider store={store}>
                        <div className="flex flex-col w-screen h-screen p-10 bg-[url('/background.webp')] bg-cover bg-center">
                            <Header />
                            <App>{children}</App>
                        </div>
                    </Provider>
                </NextUIProvider>
            </body>
        </html>
    );
}
