import type { Metadata } from "next";
import { Inter, Gaegu } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const gaegu = Gaegu({
    subsets: ["latin"],
    weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ko">
            <head>
                <title>테오 플레이그라운드</title>
            </head>
            <body className={gaegu.className}>
                <div className="flex w-screen h-screen p-10 bg-[url('/background.webp')] bg-cover bg-center">
                    {children}
                </div>
            </body>
        </html>
    );
}
